name: Build and Deploy

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: youyo/aws-cdk-github-actions@v1.1.10

      - name: NPM Install For Consume Lambda
        run: cd $GITHUB_WORKSPACE/resources/consumer && npm install

      - name: NPM Install For API Lambda
        run: cd $GITHUB_WORKSPACE/resources/api && npm install

      - name: NPM Install For React Frontend
        run: cd $GITHUB_WORKSPACE/frontend && npm install

      - name: Build React Frontend
        run: cd $GITHUB_WORKSPACE/frontend && npm run build

      - name: cdk diff
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: cdk deploy
        with:
          cdk_subcommand: 'deploy'
          actions_comment: false
          args: '--require-approval never --context kubecon_cookie=${{ secrets.KUBECON_COOKIE }} '
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: cdk synth
        with:
          cdk_subcommand: 'synth'
          cdk_version: '1.16.2'
          args: "--context kubecon_cookie=${{ secrets.KUBECON_COOKIE }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
